### ISSUE TITLE
Run protocol code on IoT device (Ultron 2.0)

### ISSUE THREAD

**Issue by itamargs** [itamargs/Iot_Project#23]

**Comment by itamargs** [comment]
נווווווווו

**Comment by OriHalyo** [comment]
Move to Next iteration so we keep up

**Comment by OriHalyo** [comment]
We needs to install packages of python, we dont have enough space -> Needs to buy memory card

**Comment by itamargs** [comment]
Can't manage to install packages for python3.
need to isntall pip3 (pip for python 3) so we can use packages for python3.
pip only install packages for python 2.
