### ISSUE TITLE
FireBase Integration

### ISSUE THREAD

**Issue by itamargs** [itamargs/Iot_Project#47]
- [x] Open FireBase Account
- [x] Design Data Base functionality
- [x] Build Data Base
- [x] Send data from server to cloud
- [x] send files to google Data Storage
- [x] send data info to fireBase/fireStore
- [x] Change database from deviceID->data to masterID->deviceID-> data
- [x]  integrate firebase storage and firestore sending functions into the real database in the Master
- [x] put the url of the file in Storage into the fire store database
- [x]  Handle offline mode

**Comment by OriHalyo** [comment]
We needs the fire base will recognize which server send the files

**Comment by OriHalyo** [comment]
Can we close it?
